# Generated by Django 4.2.7 on 2023-12-01 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('shop_url_1', models.URLField(blank=True, null=True, unique=True, verbose_name='BARBORA')),
                ('shop_url_2', models.URLField(blank=True, null=True, unique=True, verbose_name='RIMI')),
                ('shop_url_3', models.URLField(blank=True, null=True, unique=True, verbose_name='AIBĖ')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodonline.category')),
            ],
            options={
                'unique_together': {('shop_url_1', 'shop_url_2', 'shop_url_3')},
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodonline.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodonline.shop')),
            ],
        ),
    ]
